version: "3"
services:
  app:
    build: .
    ports:
      - "8080:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
      - logs:/usr/src/app/logs
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

volumes:
    logs:
      name: "flask_sample_env_logs"
      driver: local

